version: "3.9"
  
services:
  backend:
    build: .
    ports:
      - "1712:1712"
    depends_on:
      - mongo
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    networks:
      - appnet

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - appnet

networks:
  appnet:
